name: Release

on:
  push:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - uses: cycjimmy/semantic-release-action@v3
        with:
          extra_plugins: |
            @semantic-release/changelog@^6.0.3
            @semantic-release/git@^10.0.1
            @semantic-release/github@^8.0.7
            @semantic-release-cargo/semantic-release-cargo@^2.1.77
            conventional-changelog-conventionalcommits@^5.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}